Repository spon-us/SponUs-iOS, pull requests merged in 2024-02, with the labels that each got.

#68 [#63] 마이페이지 / 쿠폰함 구현
  Spon-us.xcodeproj/project.pbxproj
  Spon-us/View/MyPage/CouponView.swift
  Spon-us/View/MyPage/MyView.swift
Labels: feat💜

#69 [#63] 마이페이지 / 담당자 정보 수정하기 구현
  Spon-us.xcodeproj/project.pbxproj
  Spon-us/View/MyPage/CouponView.swift
  Spon-us/View/MyPage/HonorInfoEditView.swift
  Spon-us/View/MyPage/MyView.swift
Labels: feat💜

#72 [#63] 마이페이지 / 프로필 수정 구현
  Spon-us.xcodeproj/project.pbxproj
  Spon-us.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Spon-us/Assets.xcassets/ic_back_white.imageset/Contents.json
  Spon-us/Assets.xcassets/ic_back_white.imageset/ic_back_white@1x.png
  Spon-us/Assets.xcassets/ic_back_white.imageset/ic_back_white@2x.png
  Spon-us/Assets.xcassets/ic_back_white.imageset/ic_back_white@3x.png
  Spon-us/Assets.xcassets/ic_edit.imageset/Contents.json
  Spon-us/Assets.xcassets/ic_edit.imageset/ic_edit@1x.png
  Spon-us/Assets.xcassets/ic_edit.imageset/ic_edit@2x.png
  Spon-us/Assets.xcassets/ic_edit.imageset/ic_edit@3x.png
  Spon-us/Assets.xcassets/ic_x.imageset/Contents.json
  Spon-us/Assets.xcassets/ic_x.imageset/ic_x_1x.png
  Spon-us/Assets.xcassets/ic_x.imageset/ic_x_2x.png
  Spon-us/Assets.xcassets/ic_x.imageset/ic_x_3x.png
  Spon-us/ContentView.swift
  Spon-us/Helper/ImagePicker.swift
  Spon-us/View/MyPage/CouponView.swift
  Spon-us/View/MyPage/HonorInfoEditView.swift
  Spon-us/View/MyPage/MyProfileView.swift
  Spon-us/View/MyPage/MyView.swift
  Spon-us/View/MyPage/ProfileEditView.swift
Labels: feat💜

#80 [#70] NotificationView, SavedView UI 구현
  Spon-us.xcodeproj/project.pbxproj
  Spon-us/Assets.xcassets/ic_alert.imageset/Contents.json
  Spon-us/Assets.xcassets/ic_alert.imageset/Ellipse 88.png
  Spon-us/Assets.xcassets/ic_alert.imageset/Ellipse 88@2x.png
  Spon-us/Assets.xcassets/ic_alert.imageset/Ellipse 88@3x.png
  Spon-us/View/Home/HomeView.swift
  Spon-us/View/Notification/NotificationView.swift
  Spon-us/View/Saved/SavedView.swift
Labels: feat💜

#95 [#94] 받은 제안 / 내가 받은 제안(GET) API 구현
  Spon-us.xcodeproj/project.pbxproj
  Spon-us/Model/ReceivedOffer/ReceivedViewModel.swift
  Spon-us/Model/SendOffer/ProposalModel.swift
  Spon-us/Model/SendOffer/SentViewModel.swift
  Spon-us/SponusAPI.swift
  Spon-us/View/ReceivedOffer/ProposalReceivedListView.swift
Labels: feat💜

#106 [#89] 보낸 제안 뷰에서 선택된 proposeId, 보낸 제안서 확인 뷰에 전달하는 로직 수정
  Spon-us/Model/SendOffer/ProposalDetailViewModel.swift
  Spon-us/View/SendOffer/SendOfferPostView.swift
  Spon-us/View/SendOffer/SendOfferView.swift
Labels: chore 🧹

#116 [#89] 제안한 공고 제목이 나오도록, 제안 중 상태일 때 StatusBadge 빈칸으로 변경
  Spon-us/Model/SendOffer/SentViewModel.swift
  Spon-us/View/SendOffer/SendOfferView.swift
Labels: chore 🧹

#119 [#89] 보낸 제안서 확인 / 하단 공고 데이터 API 연동
  Spon-us.xcodeproj/project.pbxproj
  Spon-us/Model/SendOffer/ProposalDetailModel.swift
  Spon-us/View/SendOffer/SendOfferPostView.swift
  Spon-us/View/SendOffer/SendOfferView.swift
Labels: feat💜

#124 [#123] 보낸 제안 이미지 연결
  Spon-us/Model/SendOffer/ProposalDetailModel.swift
  Spon-us/View/SendOffer/SendOfferPostView.swift
  Spon-us/View/SendOffer/SendOfferView.swift
Labels: chore 🧹

#125 [#89] 보낸 제안서 확인 / 프로필 이미지 크기 조절
  Spon-us.xcodeproj/project.pbxproj
  Spon-us/View/SendOffer/SendOfferPostView.swift
Labels: chore 🧹

#130 [#129] 카테고리 뷰 수정
  Spon-us.xcodeproj/project.pbxproj
  Spon-us/Model/Category/CategoryModelData.swift
  Spon-us/View/Category/CategoryView.swift
  Spon-us/View/Post/NewPostView.swift
Labels: chore 🧹

#138 [#134] 미연결 부분 주석 처리
  Spon-us.xcodeproj/project.pbxproj
  Spon-us.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Spon-us/View/Home/HomeView.swift
  Spon-us/View/MyPage/MyProfileView.swift
  Spon-us/View/Post/NewPostView.swift
  Spon-us/View/ReceivedOffer/MyNoticeDetailView.swift
  Spon-us/View/Search/SearchOfferView.swift
  Spon-us/View/Search/SearchPostView.swift
  Spon-us/View/SendOffer/SendOfferView.swift
Labels: chore 🧹

#145 [#140] 북마크 API 연동
  Spon-us.xcodeproj/project.pbxproj
  Spon-us.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Spon-us/Model/Saved/SavedListModel.swift
  Spon-us/Model/Saved/SavedListViewModel.swift
  Spon-us/Model/Saved/SavedModel.swift
  Spon-us/Model/Saved/SavedViewModel.swift
  Spon-us/SponusAPI.swift
  Spon-us/View/Category/CategoryView.swift
  Spon-us/View/Saved/SavedView.swift
Labels: feat💜

#148 [#147] 마이페이지 데이터 수정
  Spon-us/View/MyPage/MyProfileView.swift
  Spon-us/View/MyPage/MyView.swift
Labels: fix 🔨

#152 [#147] 받은 제안 API 연결
  Spon-us.xcodeproj/project.pbxproj
  Spon-us/Model/ReceivedOffer/ReceivedOfferViewModel.swift
  Spon-us/View/ReceivedOffer/ChargerInfoViewTest.swift
  Spon-us/View/ReceivedOffer/MyNoticeListView.swift
  Spon-us/View/ReceivedOffer/ProposalReceivedListView.swift
  Spon-us/View/SendOffer/ChargerInfoView.swift
Labels: chore 🧹, feat💜
